# fly.toml app configuration file generated for footy-alerts on 2024-06-07T14:48:55+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'footy-alerts'
primary_region = 'syd'

[build]

[env]
  PORT = '8080'

[http_service]
  internal_port = 3000
  force_https = false
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/health"

[[vm]]
  size = 'shared-cpu-1x'

[mounts]
  source="footyalertsdb"
  destination="/mnt/footyalertsdb"