[package]
name = "event_processor"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
notifier = { path = "../notifier" }
squiggle = { path = "../squiggle" }
store = { path = "../store" }

serde_json = "1.0.115"
thiserror = "1"
tracing = "0.1"


